name: emotion-detection-app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - opencv
  - streamlit
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tensorflow
